[package]
name = "pallet-scheduler"
version = "47.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME Scheduler pallet"
readme = "README.md"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true }
docify = { workspace = true }
frame-benchmarking = { optional = true, workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
log = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
rp-io = { workspace = true }
rp-runtime = { workspace = true }
rp-weights = { workspace = true }

[dev-dependencies]
pallet-preimage = { default-features = true, workspace = true }
rp-core = { default-features = true, workspace = true }
substrate-test-utils = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"rp-runtime/runtime-benchmarks",
]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"rp-io/std",
	"rp-runtime/std",
	"rp-weights/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-preimage/try-runtime",
	"rp-runtime/try-runtime",
]
