[package]
name = "rc-consensus-manual-seal"
version = "0.57.0"
authors.workspace = true
description = "Manual sealing engine for Substrate"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { workspace = true }
codec = { workspace = true, default-features = true }
futures = { workspace = true }
futures-timer = { workspace = true }
jsonrpsee = { features = ["client-core", "macros", "server-core"], workspace = true }
log = { workspace = true, default-features = true }
prometheus-endpoint = { default-features = true, workspace = true }
rc-client-api = { default-features = true, workspace = true }
rc-consensus = { default-features = true, workspace = true }
rc-consensus-aura = { default-features = true, workspace = true }
rc-consensus-babe = { default-features = true, workspace = true }
rc-consensus-epochs = { default-features = true, workspace = true }
rc-transaction-pool = { default-features = true, workspace = true }
rc-transaction-pool-api = { default-features = true, workspace = true }
serde = { features = ["derive"], workspace = true, default-features = true }
rp-api = { default-features = true, workspace = true }
rp-blockchain = { default-features = true, workspace = true }
rp-consensus = { default-features = true, workspace = true }
rp-consensus-aura = { default-features = true, workspace = true }
rp-consensus-babe = { default-features = true, workspace = true }
rp-consensus-slots = { default-features = true, workspace = true }
rp-core = { default-features = true, workspace = true }
rp-externalities = { default-features = true, workspace = true }
rp-inherents = { default-features = true, workspace = true }
rp-keystore = { default-features = true, workspace = true }
rp-runtime = { default-features = true, workspace = true }
rp-timestamp = { default-features = true, workspace = true }
rp-trie = { default-features = true, workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
rc-basic-authorship = { default-features = true, workspace = true }
substrate-test-runtime-client = { workspace = true }
substrate-test-runtime-transaction-pool = { workspace = true }
tokio = { features = ["macros", "rt-multi-thread"], workspace = true, default-features = true }
