[package]
name = "rc-consensus-grandpa"
version = "0.41.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage.workspace = true
repository.workspace = true
description = "Integration of the GRANDPA finality gadget into substrate."
documentation = "https://docs.rs/rc-consensus-grandpa"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ahash = { workspace = true }
array-bytes = { workspace = true, default-features = true }
async-trait = { workspace = true }
codec = { features = ["derive"], workspace = true, default-features = true }
dyn-clone = { workspace = true }
finality-grandpa = { features = ["derive-codec"], workspace = true, default-features = true }
fork-tree = { default-features = true, workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
prometheus-endpoint = { default-features = true, workspace = true }
rand = { workspace = true, default-features = true }
rc-block-builder = { default-features = true, workspace = true }
rc-chain-spec = { default-features = true, workspace = true }
rc-client-api = { default-features = true, workspace = true }
rc-client-db = { default-features = true, workspace = true }
rc-consensus = { default-features = true, workspace = true }
rc-network = { default-features = true, workspace = true }
rc-network-common = { default-features = true, workspace = true }
rc-network-gossip = { default-features = true, workspace = true }
rc-network-sync = { default-features = true, workspace = true }
rc-network-types = { default-features = true, workspace = true }
rc-telemetry = { default-features = true, workspace = true }
rc-transaction-pool-api = { default-features = true, workspace = true }
rc-utils = { default-features = true, workspace = true }
serde_json = { workspace = true, default-features = true }
rp-api = { default-features = true, workspace = true }
rp-application-crypto = { default-features = true, workspace = true }
rp-arithmetic = { default-features = true, workspace = true }
rp-blockchain = { default-features = true, workspace = true }
rp-consensus = { default-features = true, workspace = true }
rp-consensus-grandpa = { default-features = true, workspace = true }
rp-core = { default-features = true, workspace = true }
rp-crypto-hashing = { default-features = true, workspace = true }
rp-keystore = { default-features = true, workspace = true }
rp-runtime = { default-features = true, workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
finality-grandpa = { features = ["derive-codec", "test-helpers"], workspace = true, default-features = true }
rc-network-test = { workspace = true }
rp-keyring = { default-features = true, workspace = true }
rp-tracing = { default-features = true, workspace = true }
substrate-test-runtime-client = { workspace = true }
tokio = { workspace = true, default-features = true }
