[package]
name = "frame-benchmarking"
version = "46.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Macro for benchmarking a FRAME runtime."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
frame-support = { workspace = true }
frame-support-procedural = { workspace = true }
frame-system = { workspace = true }
linregress = { optional = true, workspace = true }
log = { workspace = true }
paste = { workspace = true, default-features = true }
scale-info = { features = ["derive"], workspace = true }
serde = { optional = true, workspace = true, default-features = true }
rp-api = { workspace = true }
rp-application-crypto = { workspace = true }
rp-core = { workspace = true }
rp-io = { workspace = true }
rp-runtime = { workspace = true }
rp-runtime-interface = { workspace = true }
rp-storage = { workspace = true }
static_assertions = { workspace = true, default-features = true }

[dev-dependencies]
array-bytes = { workspace = true, default-features = true }
rusty-fork = { workspace = true }
rc-client-db = { workspace = true, default-features = false }
rp-externalities = { workspace = true, default-features = false }
rp-keystore = { default-features = true, workspace = true }
rp-state-machine = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support-procedural/std",
	"frame-support/std",
	"frame-system/std",
	"linregress",
	"log/std",
	"scale-info/std",
	"serde",
	"rp-api/std",
	"rp-application-crypto/std",
	"rp-core/std",
	"rp-externalities/std",
	"rp-io/std",
	"rp-runtime-interface/std",
	"rp-runtime/std",
	"rp-state-machine/std",
	"rp-storage/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"rc-client-db/runtime-benchmarks",
	"rp-runtime/runtime-benchmarks",
]
