[package]
name = "rc-service"
version = "0.57.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage.workspace = true
repository.workspace = true
description = "Substrate service. Starts a thread that spins up the network, client, and extrinsic pool. Manages communication between them."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { workspace = true }
codec = { workspace = true, default-features = true }
directories = { workspace = true }
exit-future = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
jsonrpsee = { features = ["server"], workspace = true }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
pin-project = { workspace = true }
prometheus-endpoint = { default-features = true, workspace = true }
rand = { workspace = true, default-features = true }
rc-chain-spec = { default-features = true, workspace = true }
rc-client-api = { default-features = true, workspace = true }
rc-client-db = { workspace = true }
rc-consensus = { default-features = true, workspace = true }
rc-executor = { default-features = true, workspace = true }
rc-informant = { default-features = true, workspace = true }
rc-keystore = { default-features = true, workspace = true }
rc-network = { default-features = true, workspace = true }
rc-network-common = { default-features = true, workspace = true }
rc-network-light = { default-features = true, workspace = true }
rc-network-sync = { default-features = true, workspace = true }
rc-network-transactions = { default-features = true, workspace = true }
rc-network-types = { default-features = true, workspace = true }
rc-rpc = { default-features = true, workspace = true }
rc-rpc-server = { default-features = true, workspace = true }
rc-rpc-spec-v2 = { default-features = true, workspace = true }
rc-sysinfo = { default-features = true, workspace = true }
rc-telemetry = { default-features = true, workspace = true }
rc-tracing = { default-features = true, workspace = true }
rc-transaction-pool = { default-features = true, workspace = true }
rc-transaction-pool-api = { default-features = true, workspace = true }
rc-utils = { default-features = true, workspace = true }
schnellru = { workspace = true }
serde = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
sp-api = { default-features = true, workspace = true }
sp-blockchain = { default-features = true, workspace = true }
sp-consensus = { default-features = true, workspace = true }
sp-core = { default-features = true, workspace = true }
sp-externalities = { default-features = true, workspace = true }
sp-keystore = { default-features = true, workspace = true }
sp-runtime = { default-features = true, workspace = true }
sp-session = { default-features = true, workspace = true }
sp-state-machine = { default-features = true, workspace = true }
sp-storage = { default-features = true, workspace = true }
sp-transaction-pool = { default-features = true, workspace = true }
sp-transaction-storage-proof = { default-features = true, workspace = true }
sp-trie = { default-features = true, workspace = true }
sp-version = { default-features = true, workspace = true }
static_init = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { features = ["parking_lot", "rt-multi-thread", "time"], workspace = true, default-features = true }
tracing = { workspace = true, default-features = true }
tracing-futures = { workspace = true }

[dev-dependencies]
substrate-test-runtime = { workspace = true }
substrate-test-runtime-client = { workspace = true }

[features]
default = []
runtime-benchmarks = [
	"rc-client-db/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
