// SPDX-License-Identifier: Apache-2.0
// Copyright (C) Rostro Foundation

//! Host-function dispatch: bridge PVM [`Caller`](polkavm::Caller) ↔
//! substrate [`Function`](sp_wasm_interface::Function).
//!
//! ## Why this layer exists
//!
//! Substrate's runtime ABI is encoded by [`sp_wasm_interface`]: every host
//! function knows its own [`Signature`], reads its args from a
//! [`FunctionContext`], and returns an optional [`Value`]. The runtime side
//! is generated by [`sp_runtime_interface`] macros; for PVM targets those
//! macros emit `polkavm_import` stubs that pack args into registers
//! `A0..A5` and issue `ecalli`.
//!
//! The host side has to:
//!
//! 1. Read register values from the [`Caller`](polkavm::Caller) per the
//!    substrate [`Signature`], boxing each as the matching [`Value`].
//! 2. Wrap the caller in something implementing [`FunctionContext`] so the
//!    macro-generated [`Function::execute`] can read/write guest memory.
//! 3. Invoke [`Function::execute`] with the args.
//! 4. Write the returned [`Value`] (if any) back to `A0`.
//!
//! Step (2) is the interesting one: [`FunctionContext::read_memory_into`]
//! takes `&self`, but polkavm 0.32's `RawInstance::read_memory_into` takes
//! `&mut self`. We bridge with a [`RefCell`] inside
//! [`RostroFunctionContext`] — fully safe Rust, vs the `unsafe` reborrow
//! the GPL-3 `rc-executor-polkavm` would otherwise need.
//!
//! [`Signature`]: sp_wasm_interface::Signature
//! [`Value`]: sp_wasm_interface::Value
//! [`Function::execute`]: sp_wasm_interface::Function::execute

use alloc::string::{String, ToString};
use core::cell::RefCell;

use polkavm::{Caller, Linker, Reg};
use sp_wasm_interface::{
	Function, FunctionContext, HostFunctions, Pointer, Result as SpResult, Value, ValueType,
	WordSize,
};

/// `FunctionContext` impl backed by a [`Caller`](polkavm::Caller). Uses
/// [`RefCell`] for interior mutability so substrate's `&self` memory
/// accessors can call polkavm's `&mut self` accessors safely.
///
/// Lifetimes:
/// - `'caller` — borrow of the [`Caller`](polkavm::Caller) held by the
///   linker callback.
/// - `'a` — lifetime parameter of the polkavm caller (memory borrows).
/// - `UD` — user data type the polkavm engine was parameterised with.
pub struct RostroFunctionContext<'caller, 'a, UD: 'static> {
	caller: RefCell<&'caller mut Caller<'a, UD>>,
	/// Captured panic message from
	/// [`FunctionContext::register_panic_error_message`]. Substrate calls
	/// this just before triggering a guest trap; the message is paired
	/// with the next interrupt by the executor.
	panic_message: Option<String>,
}

impl<'caller, 'a, UD: 'static> RostroFunctionContext<'caller, 'a, UD> {
	/// Wrap a caller in a [`FunctionContext`]-compatible view.
	pub fn new(caller: &'caller mut Caller<'a, UD>) -> Self {
		Self { caller: RefCell::new(caller), panic_message: None }
	}

	/// Drain any panic message the guest registered. Called by the
	/// executor after a [`Function::execute`] returns to associate the
	/// message with the trap.
	pub fn take_panic_message(&mut self) -> Option<String> {
		self.panic_message.take()
	}
}

impl<'caller, 'a, UD: 'static> FunctionContext for RostroFunctionContext<'caller, 'a, UD> {
	fn read_memory_into(&self, address: Pointer<u8>, dest: &mut [u8]) -> SpResult<()> {
		let mut caller = self.caller.borrow_mut();
		caller
			.instance
			.read_memory_into(u32::from(address), dest)
			.map(|_| ())
			.map_err(|e| format!("read_memory_into({:#x}): {e}", u32::from(address)))
	}

	fn write_memory(&mut self, address: Pointer<u8>, data: &[u8]) -> SpResult<()> {
		let mut caller = self.caller.borrow_mut();
		caller
			.instance
			.write_memory(u32::from(address), data)
			.map_err(|e| format!("write_memory({:#x}, {} bytes): {e}", u32::from(address), data.len()))
	}

	fn allocate_memory(&mut self, size: WordSize) -> SpResult<Pointer<u8>> {
		// PVM's `sbrk` is a one-way grow (no free) — perfectly fine for a
		// substrate runtime call that's torn down at the end of execution.
		// `sbrk(0)` returns the current break without growing; `sbrk(size)`
		// extends it. The pre-growth break is the allocation address.
		// Substrate's `Option<u32>` host-fn returns hit this path.
		let mut caller = self.caller.borrow_mut();
		let before = caller
			.instance
			.sbrk(0)
			.map_err(|e| format!("sbrk(0): {e}"))?
			.expect("PVM contract: sbrk(0) always returns Some");
		match caller.instance.sbrk(size).map_err(|e| format!("sbrk({size}): {e}"))? {
			Some(_) => Ok(Pointer::new(before)),
			None => Err(format!("allocate_memory({size}): out of guest memory")),
		}
	}

	fn deallocate_memory(&mut self, _ptr: Pointer<u8>) -> SpResult<()> {
		// Substrate's allocator-via-host-fn path is a WASM-era concept;
		// under PVM the guest manages its own heap and the host-side
		// `allocate_memory` is only used to land return-by-codec results.
		// We never expect to be asked to free those — they leak with the
		// call's instance, which is fine for runtime semantics.
		Ok(())
	}

	fn register_panic_error_message(&mut self, message: &str) {
		self.panic_message = Some(message.to_string());
	}
}

// ─── Linker registration ──────────────────────────────────────────────────

/// Register every host function from `HF` against `linker`. Each function
/// is registered under its substrate name (e.g.
/// `ext_storage_set_version_1`); when the guest blob imports that symbol
/// the polkavm linker resolves it to the corresponding ecalli at
/// instantiation time.
///
/// Generic over `UD` (the polkavm user-data type) so callers can choose
/// what state to thread through host calls. The runtime executor will
/// most often use `UD = ()` and rely on substrate's thread-local
/// externalities; tests can pass a custom UD to introspect dispatch.
pub fn register_substrate_host_functions<UD, HF>(
	linker: &mut Linker<UD, String>,
) -> Result<(), polkavm::Error>
where
	UD: 'static,
	HF: HostFunctions,
{
	for function in HF::host_functions() {
		// Each `&'static dyn Function` is copy-cheap; capture it directly
		// in the closure. `define_untyped` returns &mut Self (chainable
		// builder); we discard.
		let name = function.name().as_bytes().to_vec();
		linker.define_untyped(name, move |mut caller: Caller<UD>| -> Result<(), String> {
			dispatch_substrate_function(&mut caller, function)
		})?;
	}
	Ok(())
}

/// Bridge a single substrate host-function call. Extracts args from
/// `caller`'s registers per the function's [`Signature`], builds a
/// [`RostroFunctionContext`], invokes [`Function::execute`], writes the
/// result back to `A0`.
///
/// Assumes a 64-bit PVM target (`riscv64emac-unknown-none-polkavm`),
/// which is what `substrate-wasm-builder` produces. The 32-bit-target
/// splits that upstream `rc-executor-polkavm` handles are not needed.
fn dispatch_substrate_function<UD: 'static>(
	caller: &mut Caller<UD>,
	function: &'static dyn Function,
) -> Result<(), String> {
	let signature = function.signature();
	let arg_kinds = signature.args.as_ref();

	if arg_kinds.len() > Reg::ARG_REGS.len() {
		return Err(format!(
			"host function '{}' has {} args but PVM ABI has only {} arg regs",
			function.name(),
			arg_kinds.len(),
			Reg::ARG_REGS.len()
		));
	}

	let mut args: [Value; 8] = [Value::I64(0); 8];
	for (i, kind) in arg_kinds.iter().enumerate() {
		let raw = caller.instance.reg(Reg::ARG_REGS[i]);
		args[i] = match kind {
			ValueType::I32 => Value::I32(raw as i32),
			ValueType::I64 => Value::I64(raw as i64),
			// substrate's runtime ABI does not use floats; if a host fn
			// declares one, surface a hard error rather than silently
			// truncating bits in unspecified ways.
			ValueType::F32 | ValueType::F64 => {
				return Err(format!(
					"host function '{}' uses unsupported value type {:?}",
					function.name(),
					kind
				));
			},
		};
	}
	let n_args = arg_kinds.len();

	log::trace!(
		target: "rostro_executor",
		"dispatch: name={} sig={:?} args={:?}",
		function.name(),
		signature,
		&args[..n_args],
	);

	let return_value = {
		let mut ctx = RostroFunctionContext::new(caller);
		let mut args_iter = args.iter().take(n_args).copied();
		let result = function.execute(&mut ctx, &mut args_iter);
		// Borrow on `caller` is held by `ctx`; release before we write
		// the result back below.
		if let Some(panic_msg) = ctx.take_panic_message() {
			log::debug!(target: "rostro-executor",
				"host fn '{}' registered panic message: {}",
				function.name(), panic_msg);
		}
		drop(ctx);
		result.map_err(|e| format!("host fn '{}' failed: {e}", function.name()))?
	};

	if let Some(value) = return_value {
		let raw: u64 = match value {
			Value::I32(v) => v as u32 as u64, // zero-extend, not sign-extend
			Value::I64(v) => v as u64,
			Value::F32(_) | Value::F64(_) => {
				return Err(format!(
					"host function '{}' returned unsupported value type {value:?}",
					function.name()
				));
			},
		};
		caller.instance.set_reg(Reg::A0, raw);
	}

	Ok(())
}
