// SPDX-License-Identifier: Apache-2.0
// Copyright (C) Rostro Foundation

//! Host-function dispatch: bridge PVM [`Caller`](polkavm::Caller) ↔
//! substrate [`Function`](sp_wasm_interface::Function).
//!
//! ## Why this layer exists
//!
//! Substrate's runtime ABI is encoded by [`sp_wasm_interface`]: every host
//! function knows its own [`Signature`], reads its args from a
//! [`FunctionContext`], and returns an optional [`Value`]. The runtime side
//! is generated by [`sp_runtime_interface`] macros; for PVM targets those
//! macros emit `polkavm_import` stubs that pack args into registers
//! `A0..A5` and issue `ecalli`.
//!
//! The host side has to:
//!
//! 1. Read register values from the [`Caller`](polkavm::Caller) per the
//!    substrate [`Signature`], boxing each as the matching [`Value`].
//! 2. Wrap the caller in something implementing [`FunctionContext`] so the
//!    macro-generated [`Function::execute`] can read/write guest memory.
//! 3. Invoke [`Function::execute`] with the args.
//! 4. Write the returned [`Value`] (if any) back to `A0`.
//!
//! Step (2) is the interesting one: [`FunctionContext::read_memory_into`]
//! takes `&self`, but polkavm 0.32's `RawInstance::read_memory_into` takes
//! `&mut self`. We bridge with a [`RefCell`] inside
//! [`RostroFunctionContext`] — fully safe Rust, vs the `unsafe` reborrow
//! the GPL-3 `rc-executor-polkavm` would otherwise need.
//!
//! [`Signature`]: sp_wasm_interface::Signature
//! [`Value`]: sp_wasm_interface::Value
//! [`Function::execute`]: sp_wasm_interface::Function::execute

use alloc::string::{String, ToString};
use core::cell::RefCell;

use polkavm::{Caller, Linker, Reg};
use sp_wasm_interface::{
	Function, FunctionContext, HostFunctions, Pointer, Result as SpResult, Value, ValueType,
	WordSize,
};

std::thread_local! {
	/// Last panic message registered by the guest, surviving across host-fn
	/// invocations within a single `call_inner`. The substrate runtime's
	/// `panic_handler::abort_on_panic` host fn is `#[trap_on_return]` —
	/// the message is registered *just before* the guest traps, but the
	/// `RostroFunctionContext` that captured it is dropped by the time the
	/// trap surfaces. Stashing it here lets `call_inner` pair the trap
	/// with the original panic message.
	static LAST_PANIC_MESSAGE: RefCell<Option<String>> = const { RefCell::new(None) };
}

/// Clear the per-call panic-message slot. Call once at the top of each
/// runtime invocation so panic messages from a previous call don't bleed
/// through.
pub fn reset_last_panic_message() {
	LAST_PANIC_MESSAGE.with(|cell| *cell.borrow_mut() = None);
}

/// Drain the most recent panic message registered by the guest, if any.
/// Called by `call_inner` on `CallError::Trap` to enrich the error.
pub fn take_last_panic_message() -> Option<String> {
	LAST_PANIC_MESSAGE.with(|cell| cell.borrow_mut().take())
}

/// `FunctionContext` impl backed by a [`Caller`](polkavm::Caller). Uses
/// [`RefCell`] for interior mutability so substrate's `&self` memory
/// accessors can call polkavm's `&mut self` accessors safely.
///
/// Lifetimes:
/// - `'caller` — borrow of the [`Caller`](polkavm::Caller) held by the
///   linker callback.
/// - `'a` — lifetime parameter of the polkavm caller (memory borrows).
/// - `UD` — user data type the polkavm engine was parameterised with.
pub struct RostroFunctionContext<'caller, 'a, UD: 'static> {
	caller: RefCell<&'caller mut Caller<'a, UD>>,
	/// Captured panic message from
	/// [`FunctionContext::register_panic_error_message`]. Substrate calls
	/// this just before triggering a guest trap; the message is paired
	/// with the next interrupt by the executor.
	panic_message: Option<String>,
}

impl<'caller, 'a, UD: 'static> RostroFunctionContext<'caller, 'a, UD> {
	/// Wrap a caller in a [`FunctionContext`]-compatible view.
	pub fn new(caller: &'caller mut Caller<'a, UD>) -> Self {
		Self { caller: RefCell::new(caller), panic_message: None }
	}

	/// Drain any panic message the guest registered. Called by the
	/// executor after a [`Function::execute`] returns to associate the
	/// message with the trap.
	pub fn take_panic_message(&mut self) -> Option<String> {
		self.panic_message.take()
	}
}

impl<'caller, 'a, UD: 'static> FunctionContext for RostroFunctionContext<'caller, 'a, UD> {
	fn read_memory_into(&self, address: Pointer<u8>, dest: &mut [u8]) -> SpResult<()> {
		let mut caller = self.caller.borrow_mut();
		caller
			.instance
			.read_memory_into(u32::from(address), dest)
			.map(|_| ())
			.map_err(|e| format!("read_memory_into({:#x}): {e}", u32::from(address)))
	}

	fn write_memory(&mut self, address: Pointer<u8>, data: &[u8]) -> SpResult<()> {
		let mut caller = self.caller.borrow_mut();
		caller
			.instance
			.write_memory(u32::from(address), data)
			.map_err(|e| format!("write_memory({:#x}, {} bytes): {e}", u32::from(address), data.len()))
	}

	fn allocate_memory(&mut self, size: WordSize) -> SpResult<Pointer<u8>> {
		// PVM's `sbrk` is a one-way grow (no free) — perfectly fine for a
		// substrate runtime call that's torn down at the end of execution.
		//
		// Layout contract enforced here, matching what substrate's
		// `RuntimeAllocator` in sp-io/src/global_alloc.rs expects from a
		// freeing-bump-style host allocator:
		//
		// 1. **8-byte header** before every returned pointer. The runtime
		//    writes a 2-byte alignment-offset at `(returned_ptr - 2)`; the
		//    header is the scratch space that absorbs that write. Without
		//    it the offset bytes overwrite the previous allocation's tail
		//    (observed: zeroed bytes mid-buffer in JSON output from
		//    GenesisBuilder_get_preset).
		//
		// 2. **8-byte returned-pointer alignment.** The runtime calls
		//    `align_offset(align)` on what we return and applies the shift;
		//    if our pointer isn't already 8-aligned the shift then offsets
		//    the 2-byte offset-write into the *middle* of the data buffer,
		//    corrupting in-flight allocations a second way.
		//
		// 3. **8-byte heap-top alignment after sbrk.** Pad the payload up
		//    to a multiple of 8 so the next allocation also lands on an
		//    8-byte boundary — without this padding, e.g. `malloc(12382)`
		//    leaves the break 6 bytes off and the next caller hits problem
		//    (2) above.
		//
		// Together these mirror the WASM-path freeing-bump allocator's
		// 8-byte header + 8-byte alignment invariants.
		const ALIGN: u32 = 8;
		const HEADER_SIZE: u32 = 8;
		let payload_padded = size
			.checked_add(ALIGN - 1)
			.map(|x| x & !(ALIGN - 1))
			.ok_or_else(|| format!("allocate_memory({size}): payload-pad overflow"))?;
		let mut caller = self.caller.borrow_mut();
		let before = caller
			.instance
			.sbrk(0)
			.map_err(|e| format!("sbrk(0): {e}"))?
			.expect("PVM contract: sbrk(0) always returns Some");
		// Leading pad so that `before + leading_pad + HEADER_SIZE` is
		// 8-aligned (i.e. the returned pointer is 8-aligned).
		let leading_pad = (ALIGN - ((before + HEADER_SIZE) & (ALIGN - 1))) & (ALIGN - 1);
		let total = leading_pad
			.checked_add(HEADER_SIZE)
			.and_then(|x| x.checked_add(payload_padded))
			.ok_or_else(|| format!("allocate_memory({size}): total-size overflow"))?;
		match caller.instance.sbrk(total).map_err(|e| format!("sbrk({total}): {e}"))? {
			Some(_) => Ok(Pointer::new(before + leading_pad + HEADER_SIZE)),
			None => Err(format!("allocate_memory({size}): out of guest memory")),
		}
	}

	fn deallocate_memory(&mut self, _ptr: Pointer<u8>) -> SpResult<()> {
		// Substrate's allocator-via-host-fn path is a WASM-era concept;
		// under PVM the guest manages its own heap and the host-side
		// `allocate_memory` is only used to land return-by-codec results.
		// We never expect to be asked to free those — they leak with the
		// call's instance, which is fine for runtime semantics.
		Ok(())
	}

	fn register_panic_error_message(&mut self, message: &str) {
		// Stash on the per-context slot (kept for symmetry with the
		// substrate API contract) and also push to the thread-local so
		// `call_inner` can surface the message in the trap error.
		let owned = message.to_string();
		LAST_PANIC_MESSAGE.with(|cell| *cell.borrow_mut() = Some(owned.clone()));
		self.panic_message = Some(owned);
	}
}

// ─── Linker registration ──────────────────────────────────────────────────

/// Register every host function from `HF` against `linker`. Each function
/// is registered under its substrate name (e.g.
/// `ext_storage_set_version_1`); when the guest blob imports that symbol
/// the polkavm linker resolves it to the corresponding ecalli at
/// instantiation time.
///
/// Generic over `UD` (the polkavm user-data type) so callers can choose
/// what state to thread through host calls. The runtime executor will
/// most often use `UD = ()` and rely on substrate's thread-local
/// externalities; tests can pass a custom UD to introspect dispatch.
pub fn register_substrate_host_functions<UD, HF>(
	linker: &mut Linker<UD, String>,
) -> Result<(), polkavm::Error>
where
	UD: 'static,
	HF: HostFunctions,
{
	for function in HF::host_functions() {
		// Each `&'static dyn Function` is copy-cheap; capture it directly
		// in the closure. `define_untyped` returns &mut Self (chainable
		// builder); we discard.
		let name = function.name().as_bytes().to_vec();
		linker.define_untyped(name, move |mut caller: Caller<UD>| -> Result<(), String> {
			dispatch_substrate_function(&mut caller, function)
		})?;
	}
	Ok(())
}

/// Canonical import symbols of the RVM reserved-range intrinsics
/// (`ROSTRO_INTRINSIC_*`, ecalli 100..1023). One entry per pinned import
/// declared by runtime-side code: the verify class lives in
/// `rostro-guest-crypto/src/ecalli.rs` (IDs 110-114, 123), the curve class
/// in `rostro-curve-hooks/src/ecalli.rs` (IDs 115-119, 124-128) — those
/// modules are the source of truth for names; keep this list in sync. The
/// facade-test fixture instantiates through this registration, so a
/// missing entry fails that harness loudly.
pub const ROSTRO_INTRINSIC_IMPORT_SYMBOLS: &[&str] = &[
	// verify class (rostro-guest-crypto)
	"rostro_mldsa65_verify",
	"rostro_p521_verify_prehash",
	"rostro_p256_verify_prehash",
	"rostro_slhdsa128s_verify",
	"rostro_bls381_pairing_check",
	"rostro_secp256k1_recover",
	// curve class (rostro-curve-hooks)
	"rostro_bls381_g1_msm",
	"rostro_bls381_g2_msm",
	"rostro_bls381_multi_miller_loop",
	"rostro_bls381_final_exp",
	"rostro_bandersnatch_te_msm",
	"rostro_bandersnatch_te_mul_projective",
	"rostro_bandersnatch_sw_msm",
	"rostro_bandersnatch_sw_mul_projective",
	"rostro_bls381_g1_mul_projective",
	"rostro_bls381_g2_mul_projective",
];

/// Register inert stubs for every reserved-range intrinsic import symbol.
///
/// Stubs satisfy instantiation-time import resolution ONLY: the
/// interpreter intercepts reserved-range ecalli inline in
/// `FAST_OP_ECALLI`, so a stub actually executing means this node's VM
/// does not implement the intrinsic the blob was built against — a hard
/// error by design (deployment invariant: node before runtime; an old
/// runtime on a new node just interprets, a new runtime on an old node
/// must fail loudly, never fall back silently).
pub fn register_rostro_intrinsic_stubs<UD>(
	linker: &mut Linker<UD, String>,
) -> Result<(), polkavm::Error>
where
	UD: 'static,
{
	for name in ROSTRO_INTRINSIC_IMPORT_SYMBOLS {
		linker.define_untyped(
			name.as_bytes().to_vec(),
			move |_caller: Caller<UD>| -> Result<(), String> {
				Err(format!(
					"unreachable: {name} is a reserved-range RVM intrinsic dispatched inline \
					 by the interpreter; a stub executing means this node's VM lacks the \
					 intrinsic this runtime was built against"
				))
			},
		)?;
	}
	Ok(())
}

/// Bridge a single substrate host-function call. Extracts args from
/// `caller`'s registers per the function's [`Signature`], builds a
/// [`RostroFunctionContext`], invokes [`Function::execute`], writes the
/// result back to `A0`.
///
/// Assumes a 64-bit PVM target (`riscv64emac-unknown-none-polkavm`),
/// which is what `substrate-wasm-builder` produces. The 32-bit-target
/// splits that upstream `rc-executor-polkavm` handles are not needed.
fn dispatch_substrate_function<UD: 'static>(
	caller: &mut Caller<UD>,
	function: &'static dyn Function,
) -> Result<(), String> {
	let signature = function.signature();
	let arg_kinds = signature.args.as_ref();

	if arg_kinds.len() > Reg::ARG_REGS.len() {
		return Err(format!(
			"host function '{}' has {} args but PVM ABI has only {} arg regs",
			function.name(),
			arg_kinds.len(),
			Reg::ARG_REGS.len()
		));
	}

	let mut args: [Value; 8] = [Value::I64(0); 8];
	for (i, kind) in arg_kinds.iter().enumerate() {
		let raw = caller.instance.reg(Reg::ARG_REGS[i]);
		args[i] = match kind {
			ValueType::I32 => Value::I32(raw as i32),
			ValueType::I64 => Value::I64(raw as i64),
			// substrate's runtime ABI does not use floats; if a host fn
			// declares one, surface a hard error rather than silently
			// truncating bits in unspecified ways.
			ValueType::F32 | ValueType::F64 => {
				return Err(format!(
					"host function '{}' uses unsupported value type {:?}",
					function.name(),
					kind
				));
			},
		};
	}
	let n_args = arg_kinds.len();

	log::trace!(
		target: "rostro_executor",
		"dispatch: name={} sig={:?} args={:?}",
		function.name(),
		signature,
		&args[..n_args],
	);

	let return_value = {
		let mut ctx = RostroFunctionContext::new(caller);
		let mut args_iter = args.iter().take(n_args).copied();
		let result = function.execute(&mut ctx, &mut args_iter);
		// Borrow on `caller` is held by `ctx`; release before we write
		// the result back below. The message is also stashed on the
		// thread-local `LAST_PANIC_MESSAGE` slot by
		// `register_panic_error_message`, so `call_inner` can pair it
		// with the trap that follows.
		if let Some(panic_msg) = ctx.take_panic_message() {
			log::debug!(target: "rostro_executor",
				"host fn '{}' registered panic message: {}",
				function.name(), panic_msg);
		}
		drop(ctx);
		result.map_err(|e| format!("host fn '{}' failed: {e}", function.name()))?
	};

	if let Some(value) = return_value {
		let raw: u64 = match value {
			Value::I32(v) => v as u32 as u64, // zero-extend, not sign-extend
			Value::I64(v) => v as u64,
			Value::F32(_) | Value::F64(_) => {
				return Err(format!(
					"host function '{}' returned unsupported value type {value:?}",
					function.name()
				));
			},
		};
		caller.instance.set_reg(Reg::A0, raw);
	}

	Ok(())
}
