[package]
name = "frame-election-provider-support"
version = "46.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "election provider supporting traits"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
frame-election-provider-solution-type = { default-features = true, workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
rp-arithmetic = { workspace = true }
rp-core = { workspace = true }
rp-npos-elections = { workspace = true }
rp-runtime = { workspace = true }
rp-std = { workspace = true }


[dev-dependencies]
rand = { features = ["small_rng"], workspace = true, default-features = true }
rp-io = { default-features = true, workspace = true }
rp-npos-elections = { default-features = true, workspace = true }

[features]
default = ["std"]
fuzz = ["default"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"rp-arithmetic/std",
	"rp-core/std",
	"rp-npos-elections/std",
	"rp-runtime/std",
	"rp-std/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"rp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"rp-runtime/try-runtime",
]
