// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Rostro Foundation contributors

//! Share descriptor + 256-bit ID types + block-anchored TTL helpers.
//!
//! ## Identifiers
//!
//! Four 32-byte newtypes carry distinct semantics so the type system
//! prevents accidental misuse:
//!
//! - [`MessageId`]: random per-message identifier. Generated by the
//!   sender; opaque to relays.
//! - [`GroupId`]: random per-group identifier, stable for the life of
//!   the group. The chain does not know groups exist; the group ID
//!   lives entirely in MLS state + relay traffic metadata.
//! - [`RelayPubkey`]: Ed25519 pubkey of a relay node (libp2p
//!   node-identity key).
//! - [`PickupKey`]: 32-byte DHT lookup key under which a recipient
//!   queries for waiting shares. Computed via domain-separated
//!   blake2_256 over either the recipient's pubkey (for pairwise
//!   DMs) or the group ID (for group messages). Pairwise and group
//!   pickup keys cannot collide because of domain separation.
//!
//! ## Pickup-key derivation
//!
//! Pairwise: `blake2_256("rostro/chat/pickup-key/pair/v1" || recipient_pubkey)`
//!
//! Group: `blake2_256("rostro/chat/pickup-key/group/v1" || group_id_bytes)`
//!
//! Both yield uniform-looking 32-byte values. A relay observing
//! pickup keys cannot distinguish pairwise from group traffic without
//! prior knowledge of the recipient pubkey or group ID. Recipients
//! reproduce the same hash locally to query the DHT.
//!
//! ## TTL
//!
//! All durations are local-wall-clock. The chat layer's default TTL is
//! [`CHAT_TTL_SECONDS`] (3 days). Senders stamp
//! [`ShareDescriptor::expires_at_unix_ts`] with
//! `now_unix_seconds() + CHAT_TTL_SECONDS` (or a shorter window if
//! desired); each gossip participant runs its own periodic sweep
//! against its own local clock. NTP-class clock skew between nodes is
//! absorbed by replication — with R copies of each shard across
//! bucket-subscribed nodes, the recipient just needs one replica to
//! still be live; sub-minute skew is invisible against a 72-hour
//! window.
//!
//! Decoupling chat-shard expiry from chain block height means a chat-
//! gossip participant does NOT need to follow blocks. A node that
//! wants to be a gossip relay can run a much lighter footprint than a
//! full chain/RPC node.
//!
//! ## Receive-time bounds
//!
//! When a node receives a new share, it MUST reject the descriptor if
//! either of two bounds is violated:
//!
//! - `expires_at_unix_ts - now > MAX_TTL_SLOP_SECONDS` — bounds an
//!   adversarial sender stamping a far-future expiry to squat in the
//!   store. Reject anything claiming more than `CHAT_TTL_SECONDS +
//!   MAX_TTL_SLOP_SECONDS` of remaining life at receive time.
//! - `now - expires_at_unix_ts > PAST_GRACE_SECONDS` — rejects shards
//!   already expired by more than a brief grace window (handles a
//!   node whose clock briefly lags vs. the sender's).
//!
//! Both bounds are local arithmetic. No chain involvement.

use alloc::vec::Vec;
use codec::{Decode, Encode};
use sp_crypto_hashing::blake2_256;

/// Unix timestamp in seconds, as a 64-bit count. Local-clock,
/// chain-agnostic. Wide enough that wrap is not a concern within any
/// human time horizon.
pub type UnixTimestamp = u64;

/// Position of a share within a chunked message. `u8` accommodates
/// every legitimate N up to [`crate::chunk::MAX_CHUNKS`].
pub type ShareIndex = u8;

/// Default chat-message TTL in seconds. 259_200 seconds = 3 days.
/// Sender-side convention; receivers enforce against
/// [`ShareDescriptor::expires_at_unix_ts`] which can be shorter (e.g.
/// for system notifications with tighter renewal). The value is a
/// wall-clock target, not block-anchored, so changes to the chain's
/// block time have no effect on it.
pub const CHAT_TTL_SECONDS: UnixTimestamp = 3 * 24 * 60 * 60;

/// Maximum forward slop a receive may accept on top of
/// [`CHAT_TTL_SECONDS`]. A sender stamping
/// `expires_at_unix_ts > now + CHAT_TTL_SECONDS + MAX_TTL_SLOP_SECONDS`
/// is either misbehaving or has a wildly skewed clock; either way the
/// receive rejects. ~10 minutes accommodates ordinary NTP drift +
/// transport latency for a share to reach a distant relay.
pub const MAX_TTL_SLOP_SECONDS: UnixTimestamp = 600;

/// How far in the past a descriptor's expiry may be at receive time
/// before the receive rejects it as already-stale. ~1 minute handles
/// a brief clock lag on the receiving node vs. the sender's stamp.
pub const PAST_GRACE_SECONDS: UnixTimestamp = 60;

/// Domain-separation tag for pairwise-DM pickup-key derivation.
/// Bumped (e.g. `/v2`) if the layout ever changes incompatibly.
pub const PICKUP_KEY_PAIRWISE_DOMAIN: &[u8] = b"rostro/chat/pickup-key/pair/v1";

/// Domain-separation tag for group-message pickup-key derivation.
pub const PICKUP_KEY_GROUP_DOMAIN: &[u8] = b"rostro/chat/pickup-key/group/v1";

/// Domain-separation tag for dead-drop pickup-key derivation. A dead drop
/// is routed by an opaque ≤32-byte label (a callsign) instead of by
/// recipient identity; hashing the label yields a uniform 32-byte pickup
/// key indistinguishable in the store from a pairwise/group key. See
/// `docs/DOTWAVE-CHAT-DEAD-DROPS.md`.
pub const PICKUP_KEY_DEADDROP_DOMAIN: &[u8] = b"rostro/chat/pickup-key/deaddrop/v1";

/// Random per-message identifier. Sender-generated, opaque to relays.
/// 256-bit space → collision is cosmologically improbable, no
/// uniqueness check needed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Encode, Decode)]
pub struct MessageId(pub [u8; 32]);

impl MessageId {
	/// Generate a fresh `MessageId` from a CSPRNG.
	pub fn generate<R>(rng: &mut R) -> Self
	where
		R: rand_core::RngCore + rand_core::CryptoRng,
	{
		let mut bytes = [0u8; 32];
		rng.fill_bytes(&mut bytes);
		Self(bytes)
	}
}

/// Random per-group identifier, stable for the group's lifetime.
/// Chain doesn't know groups exist; this lives entirely in MLS state
/// + relay traffic metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Encode, Decode)]
pub struct GroupId(pub [u8; 32]);

impl GroupId {
	/// Generate a fresh `GroupId` from a CSPRNG. 256-bit collision
	/// probability is cosmologically negligible; no check needed.
	pub fn generate<R>(rng: &mut R) -> Self
	where
		R: rand_core::RngCore + rand_core::CryptoRng,
	{
		let mut bytes = [0u8; 32];
		rng.fill_bytes(&mut bytes);
		Self(bytes)
	}
}

/// Ed25519 pubkey of a relay node (libp2p node-identity key). 32-byte
/// raw key bytes; PeerId is derived from this on the libp2p layer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Encode, Decode)]
pub struct RelayPubkey(pub [u8; 32]);

/// Domain-separated 32-byte DHT lookup key under which a recipient
/// queries for waiting shares. See module doc for derivation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Encode, Decode)]
pub struct PickupKey(pub [u8; 32]);

impl PickupKey {
	/// Pickup key for pairwise DM to the holder of `recipient_pubkey`.
	pub fn for_pairwise(recipient_pubkey: &[u8; 32]) -> Self {
		let mut input = Vec::with_capacity(PICKUP_KEY_PAIRWISE_DOMAIN.len() + 32);
		input.extend_from_slice(PICKUP_KEY_PAIRWISE_DOMAIN);
		input.extend_from_slice(recipient_pubkey);
		Self(blake2_256(&input))
	}

	/// Pickup key for a group message addressed to `group_id`.
	pub fn for_group(group_id: &GroupId) -> Self {
		let mut input = Vec::with_capacity(PICKUP_KEY_GROUP_DOMAIN.len() + 32);
		input.extend_from_slice(PICKUP_KEY_GROUP_DOMAIN);
		input.extend_from_slice(&group_id.0);
		Self(blake2_256(&input))
	}

	/// Pickup key for a dead drop addressed to an opaque `label` (a
	/// callsign, ≤32 bytes). The sender derives this and the recipient
	/// derives the same key from the same label to poll for it — the label
	/// itself is exchanged out-of-band, never on-chain. Unlike
	/// [`Self::for_pairwise`], no key material is involved: the label is a
	/// pure routing selector decoupled from the message's encryption.
	pub fn for_deaddrop(label: &[u8]) -> Self {
		let mut input = Vec::with_capacity(PICKUP_KEY_DEADDROP_DOMAIN.len() + label.len());
		input.extend_from_slice(PICKUP_KEY_DEADDROP_DOMAIN);
		input.extend_from_slice(label);
		Self(blake2_256(&input))
	}
}

/// Wire descriptor published to the share-discovery DHT (and stored
/// alongside the share bytes at the relay). Tells a recipient enough
/// to (a) find this share, (b) know whether they have all N shares
/// of a message yet, (c) decide whether to discard a stale share.
///
/// The descriptor is **public**: relays and DHT participants see it.
/// It does NOT carry the sender's identity (that's encrypted inside
/// the Sealed Sender envelope) nor any plaintext message content
/// (that's encrypted by MLS/DR).
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub struct ShareDescriptor {
	/// Relay holding this share's bytes.
	pub relay_pubkey: RelayPubkey,
	/// Which message this share belongs to.
	pub message_id: MessageId,
	/// Position of this share within the message's N shares.
	pub share_index: ShareIndex,
	/// Total share count for this message. Recipient collects all
	/// `total_shares` before
	/// [`crate::chunk::combine_chunks_verified`].
	pub total_shares: u8,
	/// Domain-separated DHT lookup key. See [`PickupKey`].
	pub pickup_key: PickupKey,
	/// Unix-timestamp (seconds) at which the share expires.
	/// Sender-stamped at publication time; each gossip participant
	/// compares against its own local clock. NTP-class skew across
	/// nodes is absorbed by replication (with R copies of each shard
	/// across bucket-subscribed nodes, the recipient just needs one
	/// replica to still be live).
	pub expires_at_unix_ts: UnixTimestamp,
}

impl ShareDescriptor {
	/// `true` if the share has reached its expiry timestamp and should
	/// be purged. Strict greater-or-equal: at the boundary second, the
	/// share is considered expired (nodes purge, recipients ignore).
	pub fn is_expired(&self, now_unix_ts: UnixTimestamp) -> bool {
		now_unix_ts >= self.expires_at_unix_ts
	}

	/// Receive-time validation: return `false` if the descriptor's
	/// expiry is too far in the future or already too far in the past
	/// relative to `now_unix_ts`. See [`MAX_TTL_SLOP_SECONDS`] and
	/// [`PAST_GRACE_SECONDS`] for the bounds.
	///
	/// Both bounds are local arithmetic; no chain involvement.
	pub fn expiry_within_bounds(&self, now_unix_ts: UnixTimestamp) -> bool {
		expiry_within_bounds_at(self.expires_at_unix_ts, now_unix_ts)
	}
}

/// Free-function form of [`ShareDescriptor::expiry_within_bounds`],
/// for callers validating a sender-stamped expiry before a full
/// descriptor exists (e.g. a client-prepared chunk batch at the
/// distribution handoff — see [`crate::chunk::validate_prepared_batch`]).
/// One implementation so the two call sites can never drift.
pub fn expiry_within_bounds_at(
	expires_at_unix_ts: UnixTimestamp,
	now_unix_ts: UnixTimestamp,
) -> bool {
	let max_future = now_unix_ts
		.saturating_add(CHAT_TTL_SECONDS)
		.saturating_add(MAX_TTL_SLOP_SECONDS);
	if expires_at_unix_ts > max_future {
		return false;
	}
	let min_acceptable = now_unix_ts.saturating_sub(PAST_GRACE_SECONDS);
	if expires_at_unix_ts < min_acceptable {
		return false;
	}
	true
}

#[cfg(test)]
mod tests {
	use super::*;
	use rand_chacha::{rand_core::SeedableRng, ChaCha20Rng};

	fn test_rng(seed: u8) -> ChaCha20Rng {
		ChaCha20Rng::from_seed([seed; 32])
	}

	// ── ID generation + uniqueness ────────────────────────────────

	#[test]
	fn message_id_generate_produces_distinct_values() {
		let mut rng = test_rng(0x10);
		let a = MessageId::generate(&mut rng);
		let b = MessageId::generate(&mut rng);
		assert_ne!(a, b, "two CSPRNG draws should not collide on 256 bits");
	}

	#[test]
	fn group_id_generate_produces_distinct_values() {
		let mut rng = test_rng(0x11);
		let a = GroupId::generate(&mut rng);
		let b = GroupId::generate(&mut rng);
		assert_ne!(a, b);
	}

	// ── SCALE roundtrips ──────────────────────────────────────────

	#[test]
	fn message_id_scale_roundtrip() {
		let m = MessageId([0xAA; 32]);
		let encoded = m.encode();
		assert_eq!(encoded.len(), 32, "MessageId encodes to exactly 32 bytes");
		let decoded = MessageId::decode(&mut &encoded[..]).unwrap();
		assert_eq!(m, decoded);
	}

	#[test]
	fn group_id_scale_roundtrip() {
		let g = GroupId([0xBB; 32]);
		let encoded = g.encode();
		assert_eq!(encoded.len(), 32);
		let decoded = GroupId::decode(&mut &encoded[..]).unwrap();
		assert_eq!(g, decoded);
	}

	#[test]
	fn relay_pubkey_scale_roundtrip() {
		let r = RelayPubkey([0xCC; 32]);
		let encoded = r.encode();
		assert_eq!(encoded.len(), 32);
		let decoded = RelayPubkey::decode(&mut &encoded[..]).unwrap();
		assert_eq!(r, decoded);
	}

	#[test]
	fn pickup_key_scale_roundtrip() {
		let p = PickupKey([0xDD; 32]);
		let encoded = p.encode();
		assert_eq!(encoded.len(), 32);
		let decoded = PickupKey::decode(&mut &encoded[..]).unwrap();
		assert_eq!(p, decoded);
	}

	#[test]
	fn share_descriptor_scale_roundtrip() {
		let d = ShareDescriptor {
			relay_pubkey: RelayPubkey([0x11; 32]),
			message_id: MessageId([0x22; 32]),
			share_index: 3,
			total_shares: 5,
			pickup_key: PickupKey([0x33; 32]),
			expires_at_unix_ts: 1_700_000_000,
		};
		let encoded = d.encode();
		let decoded = ShareDescriptor::decode(&mut &encoded[..]).unwrap();
		assert_eq!(d, decoded);
	}

	// ── pickup-key derivation ─────────────────────────────────────

	#[test]
	fn pairwise_pickup_key_deterministic() {
		let recipient = [0x77u8; 32];
		let a = PickupKey::for_pairwise(&recipient);
		let b = PickupKey::for_pairwise(&recipient);
		assert_eq!(a, b, "same recipient must derive identical pickup key");
	}

	#[test]
	fn group_pickup_key_deterministic() {
		let group = GroupId([0x88; 32]);
		let a = PickupKey::for_group(&group);
		let b = PickupKey::for_group(&group);
		assert_eq!(a, b);
	}

	#[test]
	fn different_recipients_yield_different_pairwise_keys() {
		let r1 = [0x01u8; 32];
		let r2 = [0x02u8; 32];
		assert_ne!(PickupKey::for_pairwise(&r1), PickupKey::for_pairwise(&r2));
	}

	#[test]
	fn different_groups_yield_different_group_keys() {
		let g1 = GroupId([0x01; 32]);
		let g2 = GroupId([0x02; 32]);
		assert_ne!(PickupKey::for_group(&g1), PickupKey::for_group(&g2));
	}

	#[test]
	fn pairwise_and_group_domains_separated() {
		// Critical invariant: if a recipient's pubkey happened to
		// equal a group's ID bytes, the derived pickup keys must
		// still differ. Domain separation guarantees this.
		let collision_bytes = [0xAB; 32];
		let pair_key = PickupKey::for_pairwise(&collision_bytes);
		let group_key = PickupKey::for_group(&GroupId(collision_bytes));
		assert_ne!(
			pair_key, group_key,
			"domain separation must prevent pairwise/group pickup-key collision",
		);
	}

	// ── TTL boundary ──────────────────────────────────────────────

	fn descriptor_with_expiry(expires_at_unix_ts: UnixTimestamp) -> ShareDescriptor {
		ShareDescriptor {
			relay_pubkey: RelayPubkey([0; 32]),
			message_id: MessageId([0; 32]),
			share_index: 0,
			total_shares: 2,
			pickup_key: PickupKey([0; 32]),
			expires_at_unix_ts,
		}
	}

	#[test]
	fn is_expired_strictly_before_boundary_is_false() {
		let d = descriptor_with_expiry(100);
		assert!(!d.is_expired(99), "before boundary: not expired");
	}

	#[test]
	fn is_expired_at_boundary_is_true() {
		let d = descriptor_with_expiry(100);
		assert!(d.is_expired(100), "at boundary: expired (purge time)");
	}

	#[test]
	fn is_expired_after_boundary_is_true() {
		let d = descriptor_with_expiry(100);
		assert!(d.is_expired(150), "after boundary: expired");
	}

	#[test]
	fn is_expired_at_zero() {
		let d = descriptor_with_expiry(0);
		assert!(d.is_expired(0));
	}

	#[test]
	fn chat_ttl_constant_is_three_days() {
		// 3 days * 24 hours * 60 minutes * 60 seconds = 259_200.
		// Pin here so the constant doesn't silently drift if the
		// file is edited; design intent is a 3-day wall-clock TTL.
		assert_eq!(CHAT_TTL_SECONDS, 259_200);
		const SECONDS_PER_DAY: u64 = 86_400;
		assert_eq!(
			CHAT_TTL_SECONDS,
			3 * SECONDS_PER_DAY,
			"CHAT_TTL_SECONDS must equal 3 days",
		);
	}

	// ── receive-time bounds ───────────────────────────────────────

	#[test]
	fn expiry_within_bounds_typical_fresh_descriptor_accepts() {
		// Sender just stamped now + 72h. Receiver clock matches.
		let now: UnixTimestamp = 1_700_000_000;
		let d = descriptor_with_expiry(now + CHAT_TTL_SECONDS);
		assert!(d.expiry_within_bounds(now));
	}

	#[test]
	fn expiry_within_bounds_rejects_far_future_squatter() {
		// Adversarial sender stamps now + 1 year. Reject.
		let now: UnixTimestamp = 1_700_000_000;
		let d = descriptor_with_expiry(now + 365 * 86_400);
		assert!(!d.expiry_within_bounds(now));
	}

	#[test]
	fn expiry_within_bounds_accepts_slight_clock_skew_forward() {
		// Sender's clock runs ~5 minutes fast vs receiver. Should
		// still accept (within MAX_TTL_SLOP_SECONDS).
		let now: UnixTimestamp = 1_700_000_000;
		let d = descriptor_with_expiry(now + CHAT_TTL_SECONDS + 300);
		assert!(d.expiry_within_bounds(now));
	}

	#[test]
	fn expiry_within_bounds_rejects_clearly_expired_past() {
		// Descriptor's expiry is hours in the past. Reject.
		let now: UnixTimestamp = 1_700_000_000;
		let d = descriptor_with_expiry(now - 3600);
		assert!(!d.expiry_within_bounds(now));
	}

	#[test]
	fn expiry_within_bounds_accepts_slight_clock_skew_backward() {
		// Receiver clock briefly lags vs sender; descriptor is
		// "expired" by 30 seconds. Within PAST_GRACE_SECONDS.
		let now: UnixTimestamp = 1_700_000_000;
		let d = descriptor_with_expiry(now - 30);
		assert!(d.expiry_within_bounds(now));
	}

	#[test]
	fn expiry_within_bounds_rejects_past_beyond_grace() {
		// 5 minutes past, well beyond PAST_GRACE_SECONDS=60.
		let now: UnixTimestamp = 1_700_000_000;
		let d = descriptor_with_expiry(now - 300);
		assert!(!d.expiry_within_bounds(now));
	}
}
