// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Rostro Foundation contributors

//! Share descriptor + 256-bit ID types + block-anchored TTL helpers.
//!
//! ## Identifiers
//!
//! Four 32-byte newtypes carry distinct semantics so the type system
//! prevents accidental misuse:
//!
//! - [`MessageId`]: random per-message identifier. Generated by the
//!   sender; opaque to relays.
//! - [`GroupId`]: random per-group identifier, stable for the life of
//!   the group. The chain does not know groups exist; the group ID
//!   lives entirely in MLS state + relay traffic metadata.
//! - [`RelayPubkey`]: Ed25519 pubkey of a relay node (libp2p
//!   node-identity key).
//! - [`PickupKey`]: 32-byte DHT lookup key under which a recipient
//!   queries for waiting shares. Computed via domain-separated
//!   blake2_256 over either the recipient's pubkey (for pairwise
//!   DMs) or the group ID (for group messages). Pairwise and group
//!   pickup keys cannot collide because of domain separation.
//!
//! ## Pickup-key derivation
//!
//! Pairwise: `blake2_256("rostro/chat/pickup-key/pair/v1" || recipient_pubkey)`
//!
//! Group: `blake2_256("rostro/chat/pickup-key/group/v1" || group_id_bytes)`
//!
//! Both yield uniform-looking 32-byte values. A relay observing
//! pickup keys cannot distinguish pairwise from group traffic without
//! prior knowledge of the recipient pubkey or group ID. Recipients
//! reproduce the same hash locally to query the DHT.
//!
//! ## TTL
//!
//! All durations are block-anchored. The chat layer's default TTL is
//! [`CHAT_TTL_BLOCKS`] (~3 days at 6s blocks). Senders set
//! [`ShareDescriptor::expires_at_block`] to
//! `published_at + CHAT_TTL_BLOCKS` (or a shorter window if desired);
//! all relays purge at the exact same block boundary because expiry
//! is publication-time-anchored, not arrival-time-anchored.

use alloc::vec::Vec;
use codec::{Decode, Encode};
use sp_crypto_hashing::blake2_256;

/// Block number (Substrate-style u32 at this layer; chain-agnostic).
pub type BlockNumber = u32;

/// Position of a share within a striped message. `u8` accommodates
/// every legitimate N up to [`crate::stripe::MAX_SHARES`].
pub type ShareIndex = u8;

/// Default chat-message TTL in blocks. 43,200 blocks = 3 days at the
/// current 6s-block target (`MILLISECS_PER_BLOCK = 6_000`). Sender-
/// side convention; the relay enforces against
/// [`ShareDescriptor::expires_at_block`] which can be shorter (e.g.
/// for system notifications with tighter renewal). If the chain's
/// block time changes, revisit this constant deliberately — the
/// goal is a 3-day wall-clock TTL, not a fixed block count.
pub const CHAT_TTL_BLOCKS: BlockNumber = 43_200;

/// Domain-separation tag for pairwise-DM pickup-key derivation.
/// Bumped (e.g. `/v2`) if the layout ever changes incompatibly.
pub const PICKUP_KEY_PAIRWISE_DOMAIN: &[u8] = b"rostro/chat/pickup-key/pair/v1";

/// Domain-separation tag for group-message pickup-key derivation.
pub const PICKUP_KEY_GROUP_DOMAIN: &[u8] = b"rostro/chat/pickup-key/group/v1";

/// Random per-message identifier. Sender-generated, opaque to relays.
/// 256-bit space → collision is cosmologically improbable, no
/// uniqueness check needed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Encode, Decode)]
pub struct MessageId(pub [u8; 32]);

impl MessageId {
	/// Generate a fresh `MessageId` from a CSPRNG.
	pub fn generate<R>(rng: &mut R) -> Self
	where
		R: rand_core::RngCore + rand_core::CryptoRng,
	{
		let mut bytes = [0u8; 32];
		rng.fill_bytes(&mut bytes);
		Self(bytes)
	}
}

/// Random per-group identifier, stable for the group's lifetime.
/// Chain doesn't know groups exist; this lives entirely in MLS state
/// + relay traffic metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Encode, Decode)]
pub struct GroupId(pub [u8; 32]);

impl GroupId {
	/// Generate a fresh `GroupId` from a CSPRNG. 256-bit collision
	/// probability is cosmologically negligible; no check needed.
	pub fn generate<R>(rng: &mut R) -> Self
	where
		R: rand_core::RngCore + rand_core::CryptoRng,
	{
		let mut bytes = [0u8; 32];
		rng.fill_bytes(&mut bytes);
		Self(bytes)
	}
}

/// Ed25519 pubkey of a relay node (libp2p node-identity key). 32-byte
/// raw key bytes; PeerId is derived from this on the libp2p layer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Encode, Decode)]
pub struct RelayPubkey(pub [u8; 32]);

/// Domain-separated 32-byte DHT lookup key under which a recipient
/// queries for waiting shares. See module doc for derivation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Encode, Decode)]
pub struct PickupKey(pub [u8; 32]);

impl PickupKey {
	/// Pickup key for pairwise DM to the holder of `recipient_pubkey`.
	pub fn for_pairwise(recipient_pubkey: &[u8; 32]) -> Self {
		let mut input = Vec::with_capacity(PICKUP_KEY_PAIRWISE_DOMAIN.len() + 32);
		input.extend_from_slice(PICKUP_KEY_PAIRWISE_DOMAIN);
		input.extend_from_slice(recipient_pubkey);
		Self(blake2_256(&input))
	}

	/// Pickup key for a group message addressed to `group_id`.
	pub fn for_group(group_id: &GroupId) -> Self {
		let mut input = Vec::with_capacity(PICKUP_KEY_GROUP_DOMAIN.len() + 32);
		input.extend_from_slice(PICKUP_KEY_GROUP_DOMAIN);
		input.extend_from_slice(&group_id.0);
		Self(blake2_256(&input))
	}
}

/// Wire descriptor published to the share-discovery DHT (and stored
/// alongside the share bytes at the relay). Tells a recipient enough
/// to (a) find this share, (b) know whether they have all N shares
/// of a message yet, (c) decide whether to discard a stale share.
///
/// The descriptor is **public**: relays and DHT participants see it.
/// It does NOT carry the sender's identity (that's encrypted inside
/// the Sealed Sender envelope) nor any plaintext message content
/// (that's encrypted by MLS/DR).
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub struct ShareDescriptor {
	/// Relay holding this share's bytes.
	pub relay_pubkey: RelayPubkey,
	/// Which message this share belongs to.
	pub message_id: MessageId,
	/// Position of this share within the message's N shares.
	pub share_index: ShareIndex,
	/// Total share count for this message. Recipient collects all
	/// `total_shares` before [`crate::stripe::combine_xor`].
	pub total_shares: u8,
	/// Domain-separated DHT lookup key. See [`PickupKey`].
	pub pickup_key: PickupKey,
	/// Block at which the share expires. Publication-time-anchored:
	/// all relays purge at this exact block boundary, regardless of
	/// when they personally received the share.
	pub expires_at_block: BlockNumber,
}

impl ShareDescriptor {
	/// `true` if the share has reached its expiry boundary and should
	/// be purged. Strict greater-or-equal: at the boundary block, the
	/// share is considered expired (relays purge, recipients ignore).
	pub fn is_expired(&self, current_block: BlockNumber) -> bool {
		current_block >= self.expires_at_block
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use rand_chacha::{rand_core::SeedableRng, ChaCha20Rng};

	fn test_rng(seed: u8) -> ChaCha20Rng {
		ChaCha20Rng::from_seed([seed; 32])
	}

	// ── ID generation + uniqueness ────────────────────────────────

	#[test]
	fn message_id_generate_produces_distinct_values() {
		let mut rng = test_rng(0x10);
		let a = MessageId::generate(&mut rng);
		let b = MessageId::generate(&mut rng);
		assert_ne!(a, b, "two CSPRNG draws should not collide on 256 bits");
	}

	#[test]
	fn group_id_generate_produces_distinct_values() {
		let mut rng = test_rng(0x11);
		let a = GroupId::generate(&mut rng);
		let b = GroupId::generate(&mut rng);
		assert_ne!(a, b);
	}

	// ── SCALE roundtrips ──────────────────────────────────────────

	#[test]
	fn message_id_scale_roundtrip() {
		let m = MessageId([0xAA; 32]);
		let encoded = m.encode();
		assert_eq!(encoded.len(), 32, "MessageId encodes to exactly 32 bytes");
		let decoded = MessageId::decode(&mut &encoded[..]).unwrap();
		assert_eq!(m, decoded);
	}

	#[test]
	fn group_id_scale_roundtrip() {
		let g = GroupId([0xBB; 32]);
		let encoded = g.encode();
		assert_eq!(encoded.len(), 32);
		let decoded = GroupId::decode(&mut &encoded[..]).unwrap();
		assert_eq!(g, decoded);
	}

	#[test]
	fn relay_pubkey_scale_roundtrip() {
		let r = RelayPubkey([0xCC; 32]);
		let encoded = r.encode();
		assert_eq!(encoded.len(), 32);
		let decoded = RelayPubkey::decode(&mut &encoded[..]).unwrap();
		assert_eq!(r, decoded);
	}

	#[test]
	fn pickup_key_scale_roundtrip() {
		let p = PickupKey([0xDD; 32]);
		let encoded = p.encode();
		assert_eq!(encoded.len(), 32);
		let decoded = PickupKey::decode(&mut &encoded[..]).unwrap();
		assert_eq!(p, decoded);
	}

	#[test]
	fn share_descriptor_scale_roundtrip() {
		let d = ShareDescriptor {
			relay_pubkey: RelayPubkey([0x11; 32]),
			message_id: MessageId([0x22; 32]),
			share_index: 3,
			total_shares: 5,
			pickup_key: PickupKey([0x33; 32]),
			expires_at_block: 1_234_567,
		};
		let encoded = d.encode();
		let decoded = ShareDescriptor::decode(&mut &encoded[..]).unwrap();
		assert_eq!(d, decoded);
	}

	// ── pickup-key derivation ─────────────────────────────────────

	#[test]
	fn pairwise_pickup_key_deterministic() {
		let recipient = [0x77u8; 32];
		let a = PickupKey::for_pairwise(&recipient);
		let b = PickupKey::for_pairwise(&recipient);
		assert_eq!(a, b, "same recipient must derive identical pickup key");
	}

	#[test]
	fn group_pickup_key_deterministic() {
		let group = GroupId([0x88; 32]);
		let a = PickupKey::for_group(&group);
		let b = PickupKey::for_group(&group);
		assert_eq!(a, b);
	}

	#[test]
	fn different_recipients_yield_different_pairwise_keys() {
		let r1 = [0x01u8; 32];
		let r2 = [0x02u8; 32];
		assert_ne!(PickupKey::for_pairwise(&r1), PickupKey::for_pairwise(&r2));
	}

	#[test]
	fn different_groups_yield_different_group_keys() {
		let g1 = GroupId([0x01; 32]);
		let g2 = GroupId([0x02; 32]);
		assert_ne!(PickupKey::for_group(&g1), PickupKey::for_group(&g2));
	}

	#[test]
	fn pairwise_and_group_domains_separated() {
		// Critical invariant: if a recipient's pubkey happened to
		// equal a group's ID bytes, the derived pickup keys must
		// still differ. Domain separation guarantees this.
		let collision_bytes = [0xAB; 32];
		let pair_key = PickupKey::for_pairwise(&collision_bytes);
		let group_key = PickupKey::for_group(&GroupId(collision_bytes));
		assert_ne!(
			pair_key, group_key,
			"domain separation must prevent pairwise/group pickup-key collision",
		);
	}

	// ── TTL boundary ──────────────────────────────────────────────

	fn descriptor_with_expiry(expires_at_block: BlockNumber) -> ShareDescriptor {
		ShareDescriptor {
			relay_pubkey: RelayPubkey([0; 32]),
			message_id: MessageId([0; 32]),
			share_index: 0,
			total_shares: 2,
			pickup_key: PickupKey([0; 32]),
			expires_at_block,
		}
	}

	#[test]
	fn is_expired_strictly_before_boundary_is_false() {
		let d = descriptor_with_expiry(100);
		assert!(!d.is_expired(99), "before boundary: not expired");
	}

	#[test]
	fn is_expired_at_boundary_is_true() {
		let d = descriptor_with_expiry(100);
		assert!(d.is_expired(100), "at boundary: expired (purge time)");
	}

	#[test]
	fn is_expired_after_boundary_is_true() {
		let d = descriptor_with_expiry(100);
		assert!(d.is_expired(150), "after boundary: expired");
	}

	#[test]
	fn is_expired_block_zero() {
		let d = descriptor_with_expiry(0);
		assert!(d.is_expired(0));
	}

	#[test]
	fn chat_ttl_constant_is_three_days() {
		// 3 days * 24 hours * 60 minutes * 60 seconds / 6 seconds/block
		// = 43_200. Pin here so the constant doesn't silently drift
		// if the file is edited; design intent is a 3-day wall-clock
		// TTL anchored to the runtime's 6s block time.
		assert_eq!(CHAT_TTL_BLOCKS, 43_200);
		const SECONDS_PER_BLOCK: u64 = 6;
		const SECONDS_PER_DAY: u64 = 86_400;
		assert_eq!(
			CHAT_TTL_BLOCKS as u64 * SECONDS_PER_BLOCK,
			3 * SECONDS_PER_DAY,
			"CHAT_TTL_BLOCKS must equal 3 days at 6s/block",
		);
	}
}
