[package]
name = "rostro-frame"
version = "0.15.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://paritytech.github.io"
repository.workspace = true
description = "The single package to get you started with building frame pallets and runtimes"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# external deps
codec = { features = ["derive"], workspace = true }
frame-benchmarking = { optional = true, workspace = true }
frame-executive = { optional = true, workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-system-benchmarking = { optional = true, workspace = true }
frame-system-rpc-runtime-api = { optional = true, workspace = true }
frame-try-runtime = { optional = true, workspace = true }
scale-info = { features = ["derive"], workspace = true }
serde = { workspace = true }
rp-api = { optional = true, workspace = true }
rp-arithmetic = { workspace = true }
rp-block-builder = { optional = true, workspace = true }
rp-consensus-aura = { optional = true, workspace = true }
rp-consensus-grandpa = { optional = true, workspace = true }
rp-core = { workspace = true }
rp-genesis-builder = { optional = true, workspace = true }
rp-inherents = { optional = true, workspace = true }
rp-io = { workspace = true }
rp-keyring = { optional = true, workspace = true }
rp-offchain = { optional = true, workspace = true }
rp-runtime = { workspace = true }
rp-session = { optional = true, workspace = true }
rp-storage = { optional = true, workspace = true }
rp-transaction-pool = { optional = true, workspace = true }
rp-version = { optional = true, workspace = true }

docify = { workspace = true }
log = { workspace = true }

[features]
default = ["runtime", "std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-executive?/std",
	"frame-support/std",
	"frame-system-benchmarking?/std",
	"frame-system-rpc-runtime-api?/std",
	"frame-system/std",
	"frame-try-runtime?/std",
	"log/std",
	"scale-info/std",
	"serde/std",
	"rp-api?/std",
	"rp-arithmetic/std",
	"rp-block-builder?/std",
	"rp-consensus-aura?/std",
	"rp-consensus-grandpa?/std",
	"rp-core/std",
	"rp-genesis-builder?/std",
	"rp-inherents?/std",
	"rp-io/std",
	"rp-keyring?/std",
	"rp-offchain?/std",
	"rp-runtime/std",
	"rp-session?/std",
	"rp-storage/std",
	"rp-transaction-pool?/std",
	"rp-version?/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"rp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"rp-runtime/try-runtime",
]
experimental = ["frame-support/experimental"]
runtime = [
	"frame-executive",
	"frame-system-rpc-runtime-api",
	"rp-api",
	"rp-block-builder",
	"rp-consensus-aura",
	"rp-consensus-grandpa",
	"rp-genesis-builder",
	"rp-inherents",
	"rp-keyring",
	"rp-offchain",
	"rp-session",
	"rp-storage",
	"rp-transaction-pool",
	"rp-version",
]
