// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Rostro Foundation contributors

//! Build-time derivation of canonical_defs for the v0 well-known role types.
//!
//! Registers each role's concrete type into a `scale_info::Registry`, walks
//! the resulting `PortableRegistry` with the same canonicalization algorithm
//! the runtime recognizer uses, and writes a generated Rust source file
//! containing `pub const ROLE_*_CANONICAL_DEF: &[u8] = b"..."` declarations.
//!
//! `lib.rs` includes the generated file. Both `pallet-rostro-type-registry`
//! and `rostro-client` consume the constants from this crate, so the two
//! ends of the recognizer pipeline are guaranteed to agree on the byte
//! strings hashed into fingerprints.

// `canonicalize.rs` is `include!`d below. It uses `alloc::string::String`
// and `alloc::vec::Vec` for no_std compatibility on the lib side; in the
// build-script context (always std) we need to bring `alloc` into scope
// explicitly because std doesn't re-export it without an `extern crate`.
extern crate alloc;

use std::{env, fs, path::PathBuf};

// Re-include the canonicalize implementation as inline code; the runtime
// side `lib.rs` brings in the same file via `mod canonicalize;`. Single
// source of truth for the algorithm.
include!("src/canonicalize.rs");

use scale_info::{MetaType, Registry};
use sp_core::crypto::AccountId32;
use sp_core::H256;
use sp_runtime::{generic::Era, MultiAddress};
use sp_weights::Weight;

/// The seven v0 well-known role types we anchor at genesis. Must match the
/// pallet's `V0_WELL_KNOWN_ROLES` keys, byte-for-byte, on the role-marker
/// side.
fn well_known_types() -> Vec<(&'static str, &'static str, MetaType)> {
	vec![
		("ACCOUNT_ID_32", "account", MetaType::new::<AccountId32>()),
		("HASH_32", "hash", MetaType::new::<H256>()),
		("ERA", "era", MetaType::new::<Era>()),
		(
			"MULTIADDRESS",
			"multiaddress",
			MetaType::new::<MultiAddress<AccountId32, ()>>(),
		),
		("WEIGHT", "weight", MetaType::new::<Weight>()),
		("BALANCE_U128", "balance", MetaType::new::<u128>()),
		("BLOCK_NUMBER_U32", "block-number", MetaType::new::<u32>()),
	]
}

fn main() {
	println!("cargo:rerun-if-changed=build.rs");
	println!("cargo:rerun-if-changed=src/canonicalize.rs");

	let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
	let dest = out_dir.join("well_known_canonical_defs.rs");

	let mut registry = Registry::new();
	let entries: Vec<(&'static str, &'static str, u32)> = well_known_types()
		.into_iter()
		.map(|(constant_name, role_marker, meta)| {
			let symbol = registry.register_type(&meta);
			(constant_name, role_marker, symbol.id)
		})
		.collect();
	let portable: scale_info::PortableRegistry = registry.into();

	let mut output = String::new();
	output.push_str(
		"// AUTO-GENERATED by rostro-canonicalize/build.rs from real \
		 scale_info::TypeInfo of the well-known role types. Do not edit by \
		 hand — edits will be overwritten on the next build.\n\n",
	);

	output.push_str("/// Canonical structural definitions for the v0 well-known\n");
	output.push_str("/// role types, derived at build time from real `scale_info::TypeInfo`.\n");
	output.push_str("pub mod well_known_canonical_defs {\n");
	for (constant_name, _role, type_id) in &entries {
		let def = canonical_def(*type_id, &portable)
			.expect("canonical_def of well-known type succeeds; qed");
		output.push_str(&format!(
			"\tpub const {}: &[u8] = b\"{}\";\n",
			constant_name,
			rust_byte_string_escape(&def),
		));
	}
	output.push_str("}\n\n");

	output.push_str("/// Role markers (byte strings) for the v0 well-known roles.\n");
	output.push_str("pub mod well_known_roles {\n");
	for (constant_name, role, _) in &entries {
		output.push_str(&format!(
			"\tpub const {}: &[u8] = b\"{}\";\n",
			constant_name,
			rust_byte_string_escape(role),
		));
	}
	output.push_str("}\n\n");

	// Convenience tuple table for the pallet's V0_WELL_KNOWN_ROLES.
	output.push_str("/// `(role_marker, canonical_def)` pairs for the v0 well-known roles.\n");
	output.push_str("/// Pallet/client iterate this directly.\n");
	output.push_str(&format!(
		"pub const V0_WELL_KNOWN_ROLE_DEFS: [(&[u8], &[u8]); {}] = [\n",
		entries.len()
	));
	for (constant_name, _role, _) in &entries {
		output.push_str(&format!(
			"\t(well_known_roles::{n}, well_known_canonical_defs::{n}),\n",
			n = constant_name,
		));
	}
	output.push_str("];\n");

	fs::write(&dest, output).expect("write generated canonical_defs");
}

fn rust_byte_string_escape(s: &str) -> String {
	let mut out = String::with_capacity(s.len());
	for b in s.bytes() {
		match b {
			b'"' => out.push_str("\\\""),
			b'\\' => out.push_str("\\\\"),
			0x20..=0x7e => out.push(b as char),
			_ => out.push_str(&format!("\\x{:02x}", b)),
		}
	}
	out
}
