[package]
name = "rc-consensus-grandpa-rpc"
version = "0.41.0"
authors.workspace = true
description = "RPC extensions for the GRANDPA finality gadget"
repository.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
readme = "README.md"
homepage.workspace = true

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true, default-features = true }
finality-grandpa = { features = ["derive-codec"], workspace = true, default-features = true }
futures = { workspace = true }
jsonrpsee = { features = ["client-core", "macros", "server-core"], workspace = true }
log = { workspace = true, default-features = true }
rc-client-api = { default-features = true, workspace = true }
rc-consensus-grandpa = { default-features = true, workspace = true }
rc-rpc = { default-features = true, workspace = true }
serde = { features = ["derive"], workspace = true, default-features = true }
rp-blockchain = { default-features = true, workspace = true }
rp-core = { default-features = true, workspace = true }
rp-runtime = { default-features = true, workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rc-block-builder = { default-features = true, workspace = true }
rc-rpc = { features = ["test-helpers"], default-features = true, workspace = true }
rp-consensus-grandpa = { default-features = true, workspace = true }
rp-keyring = { default-features = true, workspace = true }
substrate-test-runtime-client = { workspace = true }
tokio = { features = ["macros"], workspace = true, default-features = true }
